version: '3'

tasks:
  default:
    silent: true
    desc: list available tasks
    cmds:
      - task -a

  run:
    aliases: [r]
    desc: build and run app
    cmds:
      - go run cmd/application/main.go --settings cmd/application/settings.json
    sources:
      - ./**/*.go

  test:
    aliases: [t]
    desc: run tests
    cmds:
      - go test ./... -v
    sources:
      - ./**/*.go

  build:
    aliases: [b]
    desc: build binary and web assets
    cmds:
      - task build-web
      - task build-go

  build-web:
    aliases: [bw]
    desc: build web assets
    cmds:
      - pnpm exec esbuild internal/application/web/ts/main.ts --bundle --outfile=internal/application/web/static/main.js --target=chrome58,firefox57,safari11,edge16
      - pnpm exec esbuild --bundle internal/application/web/css/main.css --outfile=internal/application/web/static/main.css
    sources:
      - ./**/*.ts
      - ./**/*.css
    generates:
      - internal/application/web/static/main.js
      - internal/application/web/static/main.css

  build-go:
    aliases: [bg]
    desc: build executable
    cmds:
      - go build -o bin/application cmd/application/main.go
    sources:
      - ./**/*.go
    generates:
      - bin/application

  compose-up:
    aliases: [cu]
    desc: docker compose up
    cmds:
      - docker compose -f docker-compose.dev.yaml up -d

  compose-down:
    aliases: [cd]
    desc: docker compose down
    cmds:
      - docker compose -f docker-compose.dev.yaml down

  migrate-up:
    aliases: [mu]
    desc: migrate database up
    cmds:
      - go run cmd/postgres/main.go --settings cmd/postgres/settings.json --migrate up

  migrate-down:
    aliases: [md]
    desc: migrate database down
    cmds:
      - go run cmd/postgres/main.go --settings cmd/postgres/settings.json --migrate down
