version: '3'

tasks:
  default:
    silent: true
    desc: list available tasks
    cmds:
      - task -a

  run:
    aliases: [r]
    desc: build and run app
    cmds:
      - go run application/main.go --settings application/settings.json
    sources:
      - ./**/*.go

  test:
    aliases: [t]
    desc: run tests
    cmds:
      - go test ./... -v
    sources:
      - ./**/*.go

  build:
    aliases: [b]
    desc: build executable
    cmds:
      - go build -o bin/server cmd/server/main.go

  compose-up:
    aliases: [cu]
    desc: docker compose up
    cmds:
      - docker compose -f etc/docker-compose.dev.yaml up -d

  compose-down:
    aliases: [cd]
    desc: docker compose down
    cmds:
      - docker compose -f etc/docker-compose.dev.yaml down

  migrate-up:
    aliases: [mu]
    desc: migrate database up
    cmds:
      - go run cmd/migrate/main.go -m up

  migrate-down:
    aliases: [md]
    desc: migrate database down
    cmds:
      - go run cmd/migrate/main.go -m down
