version: '3'

tasks:
  run:
    aliases: [r]
    desc: build and run app
    cmds:
      - go run cmd/server/main.go

  build:
    aliases: [b]
    desc: build executable
    cmds:
      - go build -o bin/server cmd/server/main.go

  compose-up:
    aliases: [cu]
    desc: start database container
    cmds:
      - docker compose -f docker/dev.yaml up -d

  compose-down:
    aliases: [cd]
    desc: stop database container
    cmds:
      - docker compose -f docker/dev.yaml down

  db-up:
    aliases: [up]
    desc: migrate database up
    cmds:
      - go run cmd/migrate/main.go -m up

  db-down:
    aliases: [down]
    desc: migrate database down
    cmds:
      - go run cmd/migrate/main.go -m down
